FROM ghcr.io/gem5/ubuntu-22.04_all-dependencies:v25-0
# Necessary for tzdata
ENV DEBIAN_FRONTEND=noninteractive
ARG TZ_ARG=UTC
ENV TZ=${TZ_ARG}
RUN apt-get update && apt-get install -y \
    tzdata \
    curl \
 && rm -rf /var/lib/apt/lists/*
